"""add close time and winner to games

Revision ID: d58d617145ec
Revises: c2b8fdf32724
Create Date: 2023-09-03 14:41:12.604044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58d617145ec'
down_revision: Union[str, None] = 'c2b8fdf32724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('games', sa.Column('player1_won', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'player1_won')
    op.drop_column('games', 'closed_at')
    # ### end Alembic commands ###
