"""refactor games to indicate user_id of winner

Revision ID: fa75c6b85911
Revises: eb8b262127c2
Create Date: 2023-09-03 22:12:02.981040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa75c6b85911"
down_revision: Union[str, None] = "eb8b262127c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games") as batch_op:
        batch_op.add_column(sa.Column("winner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_users_id_winner", "users", ["winner_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("player1_won")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games") as batch_op:
        batch_op.add_column(sa.Column("player1_won", sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint("fk_users_id_winner", type_="foreignkey")
        batch_op.drop_column("winner_id")
    # ### end Alembic commands ###
